name: hunger
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.8
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/kfccombo.png
   - assets/kgccombo2.png
   - assets/kfc.png
   - assets/biryani1.jpg
   - assets/biryani4.jpg
   - assets/biryani7.png
   - assets/veg1.png
   - assets/veg2.png
   - assets/veg3.jpg
   - assets/puri.png
   - assets/dosa.jpg
   - assets/idli1.JPG
   - assets/cake.png
   - assets/thali.jpg
   - assets/parota.jpg
   - assets/paneer.jpg
   - assets/biry.png
    
   

   

  

