name: hunger
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
   

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/biryani_1.jpg
   - assets/biryani_2.jpg
   - assets/biryani-3.jpg
   - assets/biryani-4.jpg
   - assets/biryani-5.jpg
   - assets/biryani-6.jpg
   - assets/hungerlogo.jpeg
   - assets/indianflag.png
   - assets/google.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts\Montserrat-Regular.ttf
        - asset: fonts\Montserrat-ExtraBold.ttf
        - asset: fonts\Montserrat-SemiBold.ttf
        - asset: fonts\Montserrat-Light.ttf
        - asset: fonts\Montserrat-ExtraBoldItalic.ttf
        - asset: fonts\Montserrat-BoldItalic.ttf
  

