name: hunger
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1
  carousel_slider: ^4.2.1
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

